### ISSUE TITLE
matters arising

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [unicodeveloper/unicodeveloper#1]
My name is Goodness Chinemerem Ezeokafor, a fullstack developer based in Jos
 Would love to connect with you Sir

**Comment by unicodeveloper** [comment]
Chief. How are things? Will certainly love to settle this matter ASAP!

**Comment by GoodnessEzeokafor** [comment]
I feel the tech community in jos is being left out😖
How do i reach you Sir ?
could you please send your WhatsApp number
